services:

  postgres:
    container_name: the_database
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - the_sarene_escape-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend:
    container_name: the_backend
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '.05'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 256M
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://resort-apiv1.thamjidthachu.dev/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  the_sarene_escape-postgres-data:
