# Generated by Django 4.2.3 on 2025-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_file_rename_comments_comment_rename_services_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
