# Generated by Django 4.2.3 on 2025-08-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
