# Generated by Django 4.2.3 on 2025-08-16 06:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='max_people',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='min_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='policy',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
