# Generated by Django 4.2.3 on 2025-08-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_location_service_max_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(default='person', max_length=256),
            preserve_default=False,
        ),
    ]
