# Generated by Django 4.2.3 on 2025-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
