# Generated by Django 4.2.3 on 2025-08-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_advertisement_created_at_advertisement_delete_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_time',
        ),
    ]
