# Generated by Django 4.2.3 on 2025-08-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_username_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
